/**
 * Bundle the cryptographic library for the browser.
 *
 * ===========================================================================
 * WHY THERE IS A BUILD STEP HERE, AND ONLY HERE.
 *
 * Everything server-side runs straight from TypeScript with no build, on
 * purpose: the source that gets reviewed is the source that runs. A browser
 * cannot do that, so the voter-facing bundle is the one exception.
 *
 * It is kept as boring as possible so the exception stays cheap to audit:
 *
 *   - one entry point, the SAME `@dvoting/crypto` the server and tests use, so
 *     there is no second implementation of any primitive to keep in sync;
 *   - no minification, so the shipped file is readable and diffable against
 *     the source;
 *   - the server-only key-generation entry point is NOT bundled — a voter's
 *     browser has no business holding issuer key material;
 *   - a SHA-256 of the output is printed, so a published bundle can be checked
 *     against a rebuild from the same commit.
 *
 * Ballot encryption has to happen on the voter's device. That is the whole
 * point of the design: this bundle is what makes it possible.
 * ===========================================================================
 *
 * Usage:  node scripts/build-web.ts
 */

import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const entry = join(root, "packages", "crypto", "src", "index.ts");
const outFile = join(root, "services", "ballot-box", "public", "dvoting-crypto.js");

const result = await build({
  entryPoints: [entry],
  outfile: outFile,
  bundle: true,
  format: "esm",
  platform: "browser",
  target: ["es2022"],
  // Readable output: a voter-facing security artefact should be inspectable.
  minify: false,
  sourcemap: false,
  legalComments: "inline",
  banner: {
    js:
      "// D-Voting cryptographic library — generated by scripts/build-web.ts.\n" +
      "// Built from packages/crypto/src, unminified so it can be diffed against source.\n" +
      "// Do not edit this file; edit the TypeScript and rebuild.\n",
  },
  metafile: true,
});

for (const warning of result.warnings) {
  console.warn(`[build-web] ${warning.text}`);
}

const bytes = await readFile(outFile);
const digest = createHash("sha256").update(bytes).digest("base64url");

// Record the hash next to the bundle so a deployment can be checked against a
// rebuild from the same commit.
await writeFile(
  `${outFile}.sha256`,
  `${digest}  dvoting-crypto.js\n`,
  "utf8",
);

console.log(`[build-web] ${(bytes.length / 1024).toFixed(1)} kB -> ${outFile}`);
console.log(`[build-web] sha256 ${digest}`);

// Guard against the server-only key generation leaking into a voter's browser.
const text = bytes.toString("utf8");
for (const forbidden of ["node:crypto", "generateIssuerKeyPair", "privateKeyToJwk"]) {
  if (text.includes(forbidden)) {
    throw new Error(
      `[build-web] refusing to ship: bundle contains "${forbidden}", which is server-only`,
    );
  }
}
console.log("[build-web] verified: no server-only key material in the bundle");
